export enum AdminActionType {
  USER_BAN = 'USER_BAN',
  USER_UNBAN = 'USER_UNBAN',
  ORDER_APPROVE = 'ORDER_APPROVE',
  ORDER_REJECT = 'ORDER_REJECT',
  PAYMENT_REFUND = 'PAYMENT_REFUND',
  BROADCAST_SEND = 'BROADCAST_SEND',
  CONFIG_UPDATE = 'CONFIG_UPDATE',
}
